version: '3.8'

volumes:
    mongodata: {}
    redisdata: {}

services:

    zartas:
        hostname: zartas
        dns:
            - "8.8.8.8"
            - "8.8.4.4"
        dns_search: ''
        tty: true
        build:
            context: .
            dockerfile: ./docker/nodejs/Dockerfile
        restart: always
        command: npm start
#        volumes:
#            - .:/var/www
        working_dir: /var/www
        ports:
            - "3000:3000"
        depends_on:
            - tasongo
            - achiredis

    tasongo:
        hostname: tasongo
        dns:
            - "8.8.8.8"
            - "8.8.4.4"
        dns_search: ''
        tty: true
        image: mongo:5.0
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            - mongodata:/data/db

    achiredis:
        hostname: achiredis
        dns:
            - "8.8.8.8"
            - "8.8.4.4"
        dns_search: ''
        tty: true
        image: redis:7.0-alpine
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redisdata:/data